apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xqlexct3e-go
  janus-idp.io/tekton: xqlexct3e-go
  backstage.io/kubernetes-id: xqlexct3e-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xqlexct3e-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
